server:
  port: 8761   # Default Eureka dashboard port

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false # Server should not register itself
    fetch-registry: false
